development:
  bucket: 'coworkscape-dev'
  access_key_id: ''
  secret_access_key: ''
  s3_host_name: s3-ap-northeast-1.amazonaws.com
test:
  bucket: 'coworkscape-test'
  access_key_id: ''
  secret_access_key: ''
  s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
  bucket: 'coworkscape-pro'
  access_key_id: ''
  secret_access_key: ''
  s3_host_name: s3-ap-northeast-1.amazonaws.com